# Generated by Django 3.1.2 on 2020-11-18 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.CharField(max_length=18, verbose_name='编号')),
                ('astatus', models.CharField(choices=[('uncommitted', '未提交'), ('applying', '申请中'), ('verify', '待确认'), ('waiting', '待报销'), ('perfect', '已报销')], default='未提交', max_length=20, verbose_name='申请状态')),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '申请记录',
                'verbose_name_plural': '申请记录',
                'db_table': 'apply',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid', models.CharField(max_length=20)),
                ('hname', models.CharField(max_length=100)),
                ('isDelete', models.BooleanField()),
            ],
            options={
                'db_table': 'hospital',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=20)),
                ('pw', models.CharField(max_length=16)),
                ('mname', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('auditer', '审核人'), ('manager', '审核管理人'), ('admin', '后台管理员'), ('checker', '收单员')], max_length=20, verbose_name='身份')),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'manager',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stype', models.CharField(max_length=20)),
                ('sid', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField()),
            ],
            options={
                'db_table': 'section',
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utype', models.CharField(max_length=20)),
                ('limit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('change', models.IntegerField(default=10)),
            ],
            options={
                'db_table': 'usertype',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20, verbose_name='姓名')),
                ('uid', models.CharField(max_length=18, unique=True, verbose_name='身份证/账号')),
                ('password', models.CharField(max_length=16, verbose_name='密码')),
                ('tel', models.CharField(max_length=11, verbose_name='手机号')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=10, verbose_name='性别')),
                ('money', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='报销金额')),
                ('age', models.PositiveIntegerField(default=1, verbose_name='年龄')),
                ('address', models.CharField(default='北京', max_length=20, verbose_name='省份')),
                ('isDelete', models.BooleanField(default=False, verbose_name='三元态')),
                ('utype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.usertype')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(max_length=10)),
                ('rtime', models.DateField(auto_now=True)),
                ('money', models.DecimalField(decimal_places=2, max_digits=8)),
                ('msg', models.CharField(max_length=200)),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.apply')),
            ],
            options={
                'db_table': 'record',
            },
        ),
        migrations.CreateModel(
            name='Ratio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField(default=10)),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.section')),
                ('utype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.usertype')),
            ],
            options={
                'db_table': 'ratio',
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(max_length=10)),
                ('dtime', models.DateField()),
                ('type', models.CharField(choices=[('change', '转诊单'), ('register', '挂号费'), ('cost', '发票'), ('extra', '补充')], max_length=20, verbose_name='类型')),
                ('money', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('hname', models.CharField(max_length=20, null=True)),
                ('dstatus', models.CharField(choices=[('verify', '验证'), ('success', '合格'), ('fail', '不合格')], default='验证', max_length=20, verbose_name='状态')),
                ('folder', models.ImageField(upload_to='')),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.record')),
                ('sid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.section')),
            ],
            options={
                'db_table': 'detail',
            },
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auid', models.CharField(max_length=10)),
                ('austatus', models.CharField(choices=[('finish', '完成'), ('undo', '撤销')], default='完成', max_length=10, verbose_name='状态')),
                ('autime', models.DateTimeField(auto_now_add=True)),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.apply')),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.manager')),
            ],
            options={
                'db_table': 'audit',
            },
        ),
        migrations.AddField(
            model_name='apply',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.user'),
        ),
    ]
